// Centralized icon registry — named imports so Vite tree-shakes to ONLY these
// icons instead of bundling the entire lucide library (~128 kB gzip -> a few kB).
// Access is via a Proxy so BOTH `icons.Name` and dynamic `icons[dataDrivenName]`
// work, and any unknown name degrades gracefully to a Circle instead of crashing.
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Bell,
  BellOff,
  BookMarked,
  BookOpen,
  BookX,
  BriefcaseBusiness,
  Building2,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  CalendarOff,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Component,
  Contact,
  Copy,
  CornerDownLeft,
  CreditCard,
  Database,
  DatabaseZap,
  Download,
  Eye,
  EyeOff,
  FileText,
  FileX2,
  GraduationCap,
  Grid,
  Hash,
  History,
  IdCard,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Library,
  List,
  ListChecks,
  ListTodo,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquareQuote,
  Minus,
  Moon,
  MousePointerClick,
  PanelLeftClose,
  PanelLeftOpen,
  Pin,
  Plus,
  PlusCircle,
  Printer,
  Receipt,
  ReceiptText,
  RotateCcw,
  Save,
  ScrollText,
  Search,
  SearchX,
  Send,
  Settings2,
  Share,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SquarePlus,
  Sun,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserRound,
  Users,
  Volume2,
  VolumeX,
  Wallet,
  X,
  XCircle,
} from 'lucide-vue-next'

const registry = {
  Activity, AlertCircle, AlertTriangle, ArrowDown, ArrowRight, ArrowUp, Award, BadgeCheck, Bell, BellOff, BookMarked, BookOpen, BookX, BriefcaseBusiness, Building2, CalendarCheck2, CalendarClock, CalendarDays, CalendarHeart, CalendarOff, CalendarRange, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, CircleUser, ClipboardCheck, ClipboardList, Clock, Component, Contact, Copy, CornerDownLeft, CreditCard, Database, DatabaseZap, Download, Eye, EyeOff, FileText, FileX2, GraduationCap, Grid, Hash, History, IdCard, Info, Landmark, Layers, LayoutDashboard, LayoutGrid, Library, List, ListChecks, ListTodo, Loader2, Lock, LogIn, LogOut, Mail, MapPin, Megaphone, Menu, MessageSquareQuote, Minus, Moon, MousePointerClick, PanelLeftClose, PanelLeftOpen, Pin, Plus, PlusCircle, Printer, Receipt, ReceiptText, RotateCcw, Save, ScrollText, Search, SearchX, Send, Settings2, Share, ShieldCheck, Smartphone, Sparkles, SquarePlus, Sun, Trash2, TrendingUp, Trophy, Upload, User, UserCheck, UserRound, Users, Volume2, VolumeX, Wallet, X, XCircle,
}

export const icons = new Proxy(registry, {
  get(target, key) {
    if (typeof key === 'string') {
      if (key in target) return target[key]
      if (/^[A-Z]/.test(key)) return target.Circle // unknown icon name -> safe fallback
    }
    return target[key]
  },
  has(target, key) { return typeof key === 'string' && /^[A-Z]/.test(key) ? true : key in target },
})

export default icons
